# -*- coding: utf-8 -*-
"""parkinsons_telometry_python_and_sql

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n7plRsUj2OhK_FWUPWDa5kcMzQHehQ5P
"""

import pandas as pd
import sqlite3
import re

# Load the raw telemetry CSV exported from the UCI repository
file_path = "parkinsons_telometry_dataset/Parkinsons-Telemonitoring-ucirvine.csv"
df = pd.read_csv(file_path)

# Quick check on raw headers to catch anything that might break SQL queries later
def check_sql_headers(dataframe):
    issues = {}
    for col in dataframe.columns:
        col_issues = []
        if re.search(r'[^a-zA-Z0-9_]', col):
            col_issues.append("has special chars or spaces")
        if any(c.isupper() for c in col):
            col_issues.append("uses uppercase letters")
        if col[0].isdigit():
            col_issues.append("starts with a digit")
        if col_issues:
            issues[col] = ", ".join(col_issues)
    return issues

# Run the audit check
flagged_cols = check_sql_headers(df)
print(f"Loaded {df.shape[0]} rows across {df.shape[1]} columns.")
print(f"Header check found {len(flagged_cols)} potential SQL format issues.")

print(df.columns.tolist())

# Standardize 'subject' to 'subject_id' so it's clear this acts as our primary key
if 'subject' in df.columns:
    df.rename(columns={'subject': 'subject_id'}, inplace=True)
    print("\nUpdated 'subject' header to 'subject_id' for relational schema setup.")

# The raw dataset repeats demographic data (age, sex) on every single trial row.
# Splitting this into two relational tables to eliminate redundancy:
# 1. 'patients': unique baseline info (1 row per subject)
# 2. 'telemonitoring_trials': time-series vocal metrics & UPDRS scores

# Connect to an in-memory SQLite database
conn = sqlite3.connect(':memory:')

# Pull unique patient records
patients_df = df[['subject_id', 'age', 'sex']].drop_duplicates().reset_index(drop=True)

# Pull trial telemetry data (drop age and sex to avoid storing duplicate info)
trials_df = df.drop(columns=['age', 'sex'])

# Push normalized DataFrames into SQLite tables
patients_df.to_sql('patients', conn, if_exists='replace', index=False)
trials_df.to_sql('telemonitoring_trials', conn, if_exists='replace', index=False)

print(f"Database built successfully.")
print(f"  • 'patients' table: {len(patients_df)} unique records")
print(f"  • 'telemonitoring_trials' table: {len(trials_df)} total trial recordings")

# Query 1: Measure motor score progression per patient using SQL window functions
query_progression = """
WITH ranked_trials AS (
    SELECT
        subject_id,
        test_time,
        motor_updrs,
        -- Tag the first and last trial per patient ordered by test_time
        ROW_NUMBER() OVER (PARTITION BY subject_id ORDER BY test_time ASC) as first_trial,
        ROW_NUMBER() OVER (PARTITION BY subject_id ORDER BY test_time DESC) as last_trial
    FROM telemonitoring_trials
),
baseline_and_latest AS (
    SELECT
        subject_id,
        MAX(CASE WHEN first_trial = 1 THEN motor_updrs END) AS baseline_motor_updrs,
        MAX(CASE WHEN last_trial = 1 THEN motor_updrs END) AS latest_motor_updrs
    FROM ranked_trials
    GROUP BY subject_id
)
SELECT
    p.subject_id,
    p.age,
    CASE WHEN p.sex = 0 THEN 'Male' ELSE 'Female' END AS sex,
    COUNT(t.test_time) AS total_trials,
    ROUND(bl.baseline_motor_updrs, 2) AS initial_motor_updrs,
    ROUND(bl.latest_motor_updrs, 2) AS latest_motor_updrs,
    ROUND(bl.latest_motor_updrs - bl.baseline_motor_updrs, 2) AS motor_score_change
FROM patients p
JOIN telemonitoring_trials t ON p.subject_id = t.subject_id
JOIN baseline_and_latest bl ON p.subject_id = bl.subject_id
GROUP BY p.subject_id
ORDER BY motor_score_change DESC;
"""

# Run query and pull results into a Pandas DataFrame for display
progression_df = pd.read_sql_query(query_progression, conn)
progression_df.head(10)

# Query 2: Grouping telemetry trials into clinical severity tiers
# to measure acoustic biomarker trends (Jitter, Shimmer, NHR, HNR)
query_acoustic_tiers = """
SELECT
    CASE
        WHEN motor_updrs < 15 THEN '1. Mild (<15)'
        WHEN motor_updrs BETWEEN 15 AND 25 THEN '2. Moderate (15-25)'
        ELSE '3. Severe (>25)'
    END AS severity_tier,
    COUNT(*) AS total_recordings,
    ROUND(AVG(motor_updrs), 2) AS avg_motor_updrs,
    ROUND(AVG(total_updrs), 2) AS avg_total_updrs,
    ROUND(AVG(jitter), 5) AS avg_jitter_pct,
    ROUND(AVG(shimmer), 5) AS avg_shimmer,
    ROUND(AVG(nhr), 5) AS avg_nhr,
    ROUND(AVG(hnr), 2) AS avg_hnr
FROM telemonitoring_trials
GROUP BY severity_tier
ORDER BY severity_tier ASC;
"""

acoustic_tiers_df = pd.read_sql_query(query_acoustic_tiers, conn)
acoustic_tiers_df

# Query 3: Evaluating how age and sex correlate with motor scores and voice stability
query_demographics = """
SELECT
    CASE WHEN p.sex = 0 THEN 'Male' ELSE 'Female' END AS gender,
    CASE
        WHEN p.age < 60 THEN '< 60 yrs'
        WHEN p.age BETWEEN 60 AND 70 THEN '60-70 yrs'
        ELSE '> 70 yrs'
    END AS age_group,
    COUNT(DISTINCT p.subject_id) AS patient_count,
    ROUND(AVG(t.motor_updrs), 2) AS avg_motor_updrs,
    ROUND(AVG(t.jitter), 5) AS avg_jitter,
    ROUND(AVG(t.shimmer), 5) AS avg_shimmer
FROM patients p
JOIN telemonitoring_trials t ON p.subject_id = t.subject_id
GROUP BY gender, age_group
ORDER BY gender, age_group;
"""

demographics_df = pd.read_sql_query(query_demographics, conn)
demographics_df

import matplotlib.pyplot as plt
import seaborn as sns

# Set clean aesthetic styling
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Plot 1: Jitter across Clinical Severity Tiers
sns.barplot(
    data=acoustic_tiers_df,
    x='severity_tier',
    y='avg_jitter_pct',
    ax=axes[0],
    color='#2b5c8f'
)
axes[0].set_title('Average Vocal Jitter (%) by UPDRS Severity Tier', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Motor Severity Tier', fontsize=10)
axes[0].set_ylabel('Average Jitter (%)', fontsize=10)

# Plot 2: Top 10 Patients by Motor Score Progression (Updated for Seaborn v0.14+)
top_progressors = progression_df.head(10)
sns.barplot(
    data=top_progressors,
    x='subject_id',
    y='motor_score_change',
    hue='subject_id',       # Assign x variable to hue to fix deprecation warning
    legend=False,           # Disable redundant legend
    ax=axes[1],
    palette='Reds_r',
    order=top_progressors['subject_id']
)
axes[1].set_title('Top 10 Patients with Highest Motor Progression', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Subject ID', fontsize=10)
axes[1].set_ylabel('Motor UPDRS Change (Latest - Baseline)', fontsize=10)

plt.tight_layout()
plt.show()